#!/usr/bin/env bash

source "$DOTLY_PATH/scripts/core/_main.sh"

##? ZSH helpers
#?? 1.0.0
##?
##? Usage:
##?    zsh optimize             # Optimize ZSH
##?    zsh test_performance     # Print the current ZSH performance
##?    zsh reload_completions   # Print the current ZSH performance

pip3 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip3 install -U
