#!/usr/bin/env zsh

DIRTY="✗"
NONE="✓"

prompt_personal_pwd() {
  local -r prompt_short_dir=$("$DOTLY_PATH/bin/dot" core short_pwd)
  print -n "%F{yellow}${prompt_short_dir}"
}

prompt_personal_git() {
  [[ -n ${git_info} ]] && print -n "%F{white} on${(e)git_info[prompt]}"
}

prompt_personal_status() {
  local -r work_ip=$("$DOTLY_PATH/bin/dot" work ip)

  if [[ ${work_ip} ]]; then
    prompt_icon=" "
  else
    prompt_icon="λ"
  fi

  print -n "%(?:%F{green}{%F{white}${prompt_icon}%F{green}}:%F{red}{%F{white}${prompt_icon}%F{red}})"
}

prompt_right_personal_status() {
  local -r docker_count=$(docker ps | awk '{if(NR>1)print}' | wc -l)
  local prompt_right_text=""

  if [[ ${docker_count} -gt 0 ]]; then
    prompt_right_text="(  ${docker_count})"
  fi

  print -n "${prompt_right_text}"
}

prompt_personal_precmd() {
  (( ${+functions[git-info]} )) && git-info
}

prompt_personal_setup() {
  autoload -Uz add-zsh-hook && add-zsh-hook precmd prompt_personal_precmd

  prompt_opts=(cr percent sp subst)

  zstyle ':zim:git-info:branch' format '%F{green}%b'
  zstyle ':zim:git-info:commit' format '%c'
  zstyle ':zim:git-info:clean' format '%F{white}$NONE'
  zstyle ':zim:git-info:dirty' format '%F{yellow}$DIRTY'
  zstyle ':zim:git-info:keys' format 'prompt' ' %F{cyan}%b%c %C%D'

  PS1="\$(prompt_personal_status) \$(prompt_personal_pwd)\$(prompt_personal_git)%f "
  RPS1="\$(prompt_right_personal_status)"
}

prompt_personal_setup "${@}"
