#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Count files recursive in the current directory
#?? 1.0.0
##?
##? Usage:
##?   count_files_recursive

find . -type f -print | wc -l