#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? DDD
#?? 1.0.0
##?
##? Usage:
##?    ddd

# mkdir -p "$path/Application"
# mkdir -p "$path/Domain"
# mkdir -p "$path/Infrastructure"

mkdir {Application,Domain,Infrastructure}

echo "🧞 Created!"