#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Flat the current directory
#?? 1.0.0
##?
##? Usage:
##?    connect

docs::eval "$@"

snx -s vpn.avoristravel.com -u alejandro.ortiz
systemctl restart docker

echo "😬 Dooone!"
