#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Show the work vpn ip
#?? 1.0.0
##?
##? Usage:
##?   ip

if [[ $(ifconfig | grep tunsnx) ]]; then
  ifconfig tunsnx | awk '{ print $2}' | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}"
fi
